### PR TITLE
Total Nixification

### PR DESCRIPTION
**Pull request by teozkr**
All services have been nixified. To build and load the docker images, install [Nix](https://nixos.org/nix/), run `./nix-build.sh`, and then run `docker-compose up` as usual.

# TODO

- [x] Windows support? (unlikely, no Docker support anyway)
- [x] Mac support? (building probably works, but I have no idea whether the Docker images will be usable)
- [x] `web-frontend` fails to build ATM
- [ ] Slow rebuilds, mostly due to Docker (on my computer building and importing the Docker images without the actual components takes ~1min 10s, whereas a full non-Docker build takes ~25s and basically once in a (computer's) lifetime)
- [x] No more reloading code without a container rebuild, wouldn't be an issue if not for the above
- [x] Generate list of apps automatically (default.nix)
- [x] Generate lib dependencies automatically (workspace.nix)
- [x] Update readme with instructions on how to build, run, gc etc using nix
- [ ] Migrate Travis scripts

### CODE REVIEW

**Comment by indrif** [comment]
Tried on my mac now and get the following:
```
api-photos_1                            | standard_init_linux.go:190: exec user process caused "exec format error"
be-photo-import_1                       | standard_init_linux.go:190: exec user process caused "exec format error"
gateway_1                               | standard_init_linux.go:190: exec user process caused "exec format error"
```

**Comment by teozkr** [comment]
Looks like yarn2nix doesn't support cross-compilation at the moment. Looking into what would be required for it to function.

**Comment by teozkr** [comment]
Another (although quite ugly) alternative would be to run the `nix-build`s inside https://hub.docker.com/r/nixos/nix/.

**Comment by teozkr** [comment]
It seems to work fine(-ish) on Windows, building using WSL and running the containers in Docker for Windows.

Steps:

1. Install Docker for Windows
2. Install WSL and Ubuntu for WSL
3. From WSL, run:
```
sudo mkdir -p /etc/nix
sudo echo "use-sqlite-wal = false" >> /etc/nix/nix.conf
curl https://nixos.org/nix/install | sh
```
(SQLite's WAL needs to be disabled due to Microsoft/WSL#2395.)
4. Install Docker inside WSL following https://medium.com/@sebagomez/installing-the-docker-client-on-ubuntus-windows-subsystem-for-linux-612b392a44c4
5. From WSL, run `./docker-build.sh` (inside photo-garden)
6. Run `docker-compose up`

Notes:

* In my testing the `nix-build` is very slow inside WSL. I have no idea how much of this is due to Windows problems and how much is due to it running poorly on KVM (which is, I suppose, also a Windows problem).
* In my testing the downloads seem to fail semi-spuriously. Adding `--keep-going` to the `nix-build` invocation in `docker-build.sh` lets it continue downloading the rest, and then you can pick up the last stragglers by running it a second time. This is a one-time issue when setting up a new machine.

**Comment by teozkr** [comment]
After some testing with @indrif we got it to work on Mac by following https://github.com/LnL7/nix-docker#running-as-a-remote-builder.

**Comment by teozkr** [comment]
I think I found the Parcel issue: apparently it doesn't try to compile stuff in `node_modules` with Babel: https://github.com/parcel-bundler/parcel/blob/master/src/transforms/babel.js#L96

**Pull request merged**
